INSERT INTO journals (
  type, title, field_name, index_type, cycle, description, image_url,
  journal_level, impact_factor_label, impact_factor_value, journal_partition,
  acceptance_time, submission_deadline_text, submission_deadline_date,
  discipline_category, cas_zone, jcr_quartile, view_count,
  document_name, document_url, published
) VALUES
('SCI', '人工智能教育', '计算机信息工程', 'ESCI', '1-2个月', '人工智能教育方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/ai-education.jpg', 'ESCI', '-', NULL, '-', '预计1-2个月', '长期征稿', NULL, '计算机信息工程', '-', '-', 0, NULL, NULL, TRUE),
('SCI', '物理 Physics', '数学物理', 'SCI', '2-3个月', '物理方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/physics.jpg', 'SCI', '-', NULL, 'JCR2', '预计2-3个月', '长期征稿', NULL, '数学物理', '-', 'JCR2', 0, NULL, NULL, TRUE),
('SCI', '人工智能·环境可持续', '环境科学工程', 'SCI', '2-3个月', '人工智能与环境可持续方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/ai-environment-sustainability.jpg', 'SCI', '-', NULL, 'JCR2', '预计2-3个月', '长期征稿', NULL, '环境科学工程', '-', 'JCR2', 0, NULL, NULL, TRUE),
('SCI', '工程技术', '机械电子工程', 'SCI', '2-3个月', '工程技术方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/engineering-technology.jpg', 'SCI', '-', NULL, '中科院4区，JCR3', '预计2-3个月', '长期征稿', NULL, '机械电子工程', '中科院4区', 'JCR3', 0, NULL, NULL, TRUE),
('SCI', '神经医学', '医学', 'SCI', '2-3个月', '神经医学方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/neuroscience-medicine.jpg', 'SCI', '-', NULL, '中科院3区，JCR1', '预计2-3个月', '长期征稿', NULL, '医学', '中科院3区', 'JCR1', 0, NULL, NULL, TRUE),
('SCI', '纳米材料', '材料科学', 'SCI', '2-3个月', '纳米材料方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/nanomaterials.jpg', 'SCI', '-', NULL, '中科院4区，JCR3', '预计2-3个月', '长期征稿', NULL, '材料科学', '中科院4区', 'JCR3', 0, NULL, NULL, TRUE),
('EI', '计算机人工智能', '计算机信息工程', 'EI', '3-4个月', '计算机人工智能方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/computer-ai.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '计算机信息工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '计算机·医学', '医学', 'EI', '3-4个月', '计算机与医学交叉方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/computer-medicine.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '医学', '-', '-', 0, NULL, NULL, TRUE),
('EI', '生物医学工程', '生物学', 'EI', '3-4个月', '生物医学工程方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/biomedical-engineering.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '生物学', '-', '-', 0, NULL, NULL, TRUE),
('EI', '计算机跨学科应用', '计算机信息工程', 'EI', '3-4个月', '计算机跨学科应用方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/interdisciplinary-computing.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '计算机信息工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '电子和电气', '机械电子工程', 'EI', '3-4个月', '电子和电气方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/electronics-electrical.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '机械电子工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '能源与工程', '环境科学工程', 'EI', '3-4个月', '能源与工程方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/energy-engineering.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '环境科学工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '电子电气工程', '机械电子工程', 'EI', '3-4个月', '电子电气工程方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/electronic-electrical-engineering.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '机械电子工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '多媒体图形学', '计算机信息工程', 'EI', '3-4个月', '多媒体图形学方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/multimedia-graphics.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '计算机信息工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '能源工程', '环境科学工程', 'EI', '3-4个月', '能源工程方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/energy-engineering-blue.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '环境科学工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '工程技术与燃料', '化学工程', 'EI', '3-4个月', '工程技术与燃料方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/engineering-fuels.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '化学工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '计算机算法', '计算机信息工程', 'EI', '3-4个月', '计算机算法方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/computer-algorithms.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '计算机信息工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '人文社科跨学科', '人文社科', 'EI', '3-4个月', '人文社科跨学科方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/humanities-social-sciences.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '人文社科', '-', '-', 0, NULL, NULL, TRUE),
('EI', '电信科学', '机械电子工程', 'EI', '3-4个月', '电信科学方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/telecommunications-science.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '机械电子工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '计算机网络', '计算机信息工程', 'EI', '3-4个月', '计算机网络方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/computer-networks.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '计算机信息工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '人工智能', '计算机信息工程', 'EI', '3-4个月', '人工智能方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/artificial-intelligence.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '计算机信息工程', '-', '-', 0, NULL, NULL, TRUE),
('EI', '化学工程', '化学工程', 'EI', '3-4个月', '化学工程方向稿件征集中，欢迎提交稿件进行适配评估。', '/images/journals/chemical-engineering.jpg', 'EI', '-', NULL, '-', '预计3-4个月', '长期征稿', NULL, '化学工程', '-', '-', 0, NULL, NULL, TRUE);
